services: 
  mysql-fatek:
      container_name: mysql-fatek
      image: mysql:latest
      restart: always 
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: fatek
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        - mysql-fatek-volume:/data/db
  
  backend:
    container_name: backend-fatek
    build: ./backend
    depends_on:
      - mysql-fatek
    ports:
      - 5002:5002
    
  
  frontend:
    container_name: frontend-fatek
    build: ./frontend
    depends_on:
      - mysql-fatek
      - backend
    volumes:
      - frontend-volume:/var/www/html

  nginx:
      container_name: nginx-fatek
      build: ./nginx/
      depends_on:
      - mysql-fatek
      - backend
      - frontend
      ports:
        - 80:80
      volumes:
        - frontend-volume:/var/www/html


volumes:
  frontend-volume:
  mysql-fatek-volume: