services: 
  mongo-fatek:
      container_name: mongo-fatek
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb-fatek-volume:/data/db
      restart: always 
  
  backend:
    container_name: backend-fatek
    build: ./backend
    depends_on:
      - mongo-fatek
    ports:
      - 5002:5002
    
  
  frontend:
    container_name: frontend-fatek
    build: ./frontend
    depends_on:
      - mongo-fatek
      - backend
    volumes:
      - frontend-volume:/var/www/html

  nginx:
      container_name: nginx-fatek
      build: ./nginx/
      depends_on:
      - mongo-fatek
      - backend
      - frontend
      ports:
        - 80:80
      volumes:
        - frontend-volume:/var/www/html


volumes:
  frontend-volume:
  mongodb-fatek-volume: